### ISSUE TITLE
Socket.read and Socket.read_nonblock doesn't behaves the same

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#759]
Code:
```crystal
alter_aeon_server = "alteraeon.com"
alter_aeon_port = 3000
connection = TCPSocket.new(alter_aeon_server, alter_aeon_port)
spawn autoreader(connection)
```

Read:
```crystal
def self.autoreader(connection)
    loop do
      begin
        buff = connection.read(1024).to_s
        print buff if !buff.empty?
      rescue e : IO::EOFError
        puts "EOFError"
        sleep 0.5
      rescue e : Exception
        p e
        puts e.message
        puts e.class
        sleep 0.5
      end
    end
  end
```
Read_Nonblock:
```crystal
def self.autoreader(connection)
    loop do
      begin
        buff = connection.read_nonblock(1024).to_s
        print buff if !buff.empty?
      rescue e : IO::EOFError
        puts "EOFError"
        sleep 0.5
      rescue e : Exception
        p e
        puts e.message
        puts e.class
        sleep 0.5
      end
    end
  end
```

read behaves almost like a blocking read in that it takes much more time to "let go" of the socket when no more data is coming, read_nonblock prints the data almost instantly.

I have an issue with both when they wont actually read all the available data, which can be seen when connecting to the same server and port using telnet.

**Comment by datanoise** [comment]
Sockets are already opened with nonblocking mode, so there is not need to use `read_nonblock`. 

Your problem is that by calling `io.read(1024)` you are absolutely sure that you can read exactly 1024 bytes from the stream. If you just want to read all available bytes, you'd better use `read(s: Slice(UInt8))` API, which returns the number of bytes read. 

Also, inspecting `read_nonblock`, I think it should raise IO::EOFError on the stream end:

```diff
diff --git a/src/io/console.cr b/src/io/console.cr
index d67c61f..44d3397 100644
--- a/src/io/console.cr
+++ b/src/io/console.cr
@@ -241,7 +241,7 @@ module IO
       String.new(length) do |buffer|
         read_length = read Slice.new(buffer, length)
         if read_length == 0
-          raise "read_nonblock: read nothing"
+          raise EOFError.new
         elsif LibC.errno == LibC::EWOULDBLOCK
           raise Errno.new "exception in read_nonblock"
         else
```

**Comment by bararchy** [comment]
@datanoise that makes sense ! I was getting this issue and didn't know how to handle it

```
#<Exception:0xeb7fc0 @message="read_nonblock: read nothing", @cause=nil, @backtrace=["*raise<String>:NoReturn +70 [0]", "~fun_literal_12 +340 [0]", "~fun_literal_3 +33 [0]", "co_exit +75 [0]", "__start_context +0 [0]"]>
read_nonblock: read nothing
Exception
#<Exception:0xeb7ea0 @message="read_nonblock: read nothing", @cause=nil, @backtrace=["*raise<String>:NoReturn +70 [93]", "~fun_literal_12 +340 [93]", "~fun_literal_3 +33 [93]", "co_exit +75 [93]", "__start_context +0 [93]"]>
read_nonblock: read nothing
Exception
#<Exception:0xeb7d80 @message="read_nonblock: read nothing", @cause=nil, @backtrace=["*raise<String>:NoReturn +70 [93]", "~fun_literal_12 +340 [93]", "~fun_literal_3 +33 [93]", "co_exit +75 [93]", "__start_context +0 [93]"]>
read_nonblock: read nothing
Exception
#<Exception:0xeb7c60 @message="read_nonblock: read nothing", @cause=nil, @backtrace=["*raise<String>:NoReturn +70 [93]", "~fun_literal_12 +340 [93]", "~fun_literal_3 +33 [93]", "co_exit +75 [93]", "__start_context +0 [93]"]>
read_nonblock: read nothing
Exception
#<Exception:0xeb7b40 @message="read_nonblock: read nothing", @cause=nil, @backtrace=["*raise<String>:NoReturn +70 [93]", "~fun_literal_12 +340 [93]", "~fun_literal_3 +33 [93]", "co_exit +75 [93]", "__start_context +0 [93]"]>
read_nonblock: read nothing
Exception
#<Exception:0xeb7a20 @message="read_nonblock: read nothing", @cause=nil, @backtrace=["*raise<String>:NoReturn +70 [93]", "~fun_literal_12 +340 [93]", "~fun_literal_3 +33 [93]", "co_exit +75 [93]", "__start_context +0 [93]"]>
read_nonblock: read nothing
Exception

```

**Comment by asterite** [comment]
@bararchy What's that aeon server protocol? And why do I get strange symbols when I open this?

http://alteraeon.com:3000/

I'm talking about the ÿûFÿûZ and ÿù ...

**Comment by datanoise** [comment]
@asterite  It looks like a game for telnet client.
@bararchy I've fixed your client, but removed error handling to simplify. Please check https://gist.github.com/datanoise/6ee434ed397f4e74bfbd

**Comment by bararchy** [comment]
The server won't respond to http , its a TCP telnet like connection , you should connect to it using a simple TCP socket or telnet
As in telnet alteraeon.com<http://alteraeon.com> 3000, it will send back strings of text .

This is basically a game which is played over the net using telnet or other terminal like clients.

Sent with AquaMail for Android
http://www.aqua-mail.com

On June 8, 2015 5:59:00 PM Ary Borenszweig <notifications@github.com> wrote:

@bararchy<https://github.com/bararchy> What's that aeon server protocol? And why do I get strange symbols when I open this?

http://alteraeon.com:3000/

I'm talking about the ??F??Z and ?? ...

-

**Comment by datanoise** [comment]
@asterite while playing with this example I ran into the following compiler bug:

Compiling https://gist.github.com/datanoise/dff2c16d1d6d9b3acfb2

```
Missing hash value: "buf"
*SimpleHash(String, Crystal::MetaVar)@SimpleHash(K, V)#[]<SimpleHash(String, Crystal::MetaVar), String>:Crystal::MetaVar +688 [4459333168]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +40119 [4459238151]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +12391 [4463581591]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +12185 [4463109305]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2216 [4458073432]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +8339 [4459790739]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +1782 [4459199814]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +81523 [4459279555]
*Crystal::Call#match_block_arg<Crystal::Call, Crystal::Match>:({Array(Crystal::Var+)?, (Nil | Crystal::Type+)} | {Nil, Nil}) +5052 [4463032060]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +2742 [4463571942]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +12185 [4463109305]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2216 [4458073432]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +8339 [4459790739]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +1782 [4459199814]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Assign>:Bool +88 [4459512936]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +571 [4459198603]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +27569 [4459225601]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +13219 [4459795619]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +1782 [4459199814]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +30421 [4459228453]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +3678 [4459786078]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +1782 [4459199814]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +13219 [4459795619]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +1782 [4459199814]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +27569 [4459225601]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +12391 [4463581591]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +12185 [4463109305]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2216 [4458073432]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +8339 [4459790739]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +1782 [4459199814]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +27569 [4459225601]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +3744 [4460094912]
*Crystal::Command::run_command<Array(String)>:Nil +392 [4457884808]
*Crystal::Command::run<Array(String)>:(Nil | File | Bool | AutoflushBufferedIO(FileDescriptorIO+) | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +101 [4457860405]
main +19271 [4457858551]

Error:  you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues[0m
```

**Comment by bararchy** [comment]
@datanoise using your example , after pressing a few enters (or any other keys)
I get:

```
Error writing file: Bad file descriptor (Errno)
*Errno::new<String>:Errno +437 [5]
*TCPSocket@IO#<<<TCPSocket, String>:TCPSocket +591 [5]
main +4795 [5]
__libc_start_main +240 [5]
_start +41 [5]
 +41 [5]
```

When I wrap the wirte part with begin\rescue I get this: 
code:
```crystal
loop do
      begin
        buff = gets
        connection << buff.to_s if connection
      rescue e : Exception
        puts e
      end
    end
```
issue:
```
Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

Error writing file: Bad file descriptor

```

**Comment by bararchy** [comment]
@datanoise , Right now , using the latest fix from @asterite , there is still an issue, even when using your examples, the issue is that the read wont read the all data, here is an example.

Telnet:
![telnet](https://cloud.githubusercontent.com/assets/1631073/8052382/d6927736-0e8f-11e5-8625-634f1767fefc.png)

Code:
![screenshot from 2015-06-09 10-09-22](https://cloud.githubusercontent.com/assets/1631073/8052386/de3dfcf8-0e8f-11e5-8fa2-428dd093d503.png)

You can see the difference in the last line, in telnet it shows, in my client it wont.
Any idea why ? 

P.S
There is also some weird Unicode gibberish that isn't shown on the telnet client, but, I guess maybe if I enforce UTF8 and fix the unknown symbols issue it will be fixed.

**Comment by bararchy** [comment]
@datanoise @asterite 

I have a ruby example that works, its almost the same:
https://github.com/bararchy/aeon-client/blob/master/aeon-client.rb

The ruby example does read all the lines.

**Comment by bararchy** [comment]
Further testing this thing, this seems to be a buffer issue, when there is another ```print "something"``` after the read part:

```crystal
        if len > 0
          data = String.new(buf.buffer, len)
          print data if !data.empty?
          print "\r\n."  #<==== this thing right here
        end
```
the last line is printed, maybe an IO.flush thingy ?

**Comment by datanoise** [comment]
@bararchy Ruby's `IO.sync=` has a very overcomplicated implementation, but I agree that it would be nice to have. For your particular case, you can use `print!` instead of `print` to enforce flushing.

**Comment by jhass** [comment]
I feel like we could centralize discussion about this in a more general issue like #1276

Should we close this in favour of it and keep in mind to keep the `Socket` interface the same as the `IO` interface?

**Comment by jhass** [comment]
Ping, anyone objects closing this?

**Comment by asterite** [comment]
Nope. Let's remove read_nonblock
